import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import MovieCard from './components/movieCard';

export default function Home() {
  
  const [trendingMovies, setTrendingMovies] = useState([]);

  useEffect(() => {
    async function fetchData() {
      const response = await fetch("/api/trending");
      const data = await response.json();
      setTrendingMovies(data);
    }
    fetchData();
  }, [])
  
  return (
    <>
      <Head>
        <title>MoviesDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='max-w-screen-2xl' style={{margin: "0 auto"}}>
        <div>
          Trending
        </div>
        <div className='flex justify-center'>
          <div className='px-5 max-w-screen-2xl flex flex-row overflow-x-auto gap-x-5 gap-y-5 pb-14'>
            {
              trendingMovies.length <= 0 ? <></> : (
                trendingMovies.map((movie) => {
                  return <MovieCard poster_path={movie.poster_path} title={movie.title} release_date={movie.release_date} key={movie.id}/>
                })
              )
            }
          </div>
        </div>
      </main>
    </>
  )
}
