import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import MovieCard from './components/movieCard';
import styles from "../styles/Home.module.css"
import TopNav from './components/topNav';
import LatestTrailers from './components/latestTrailers';

export default function Home() {
  
  const [trendingMovies, setTrendingMovies] = useState([]);

  useEffect(() => {
    async function fetchData() {
      const response = await fetch("/api/trending");
      const data = await response.json();
      setTrendingMovies(data);
    }
    fetchData();
  }, [])
  
  return (
    <>
      <Head>
        <title>MoviesDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <TopNav />
        <main className='px-5 max-w-screen-xl' style={{margin: "0 auto"}}>
          <div className={[styles.searchbar, "h-80", "flex", "flex-col", "text-white", "px-10", "pt-20", "monterrat", ""].join(" ")} >
            <span>Welcome.</span>
            <span>Millions of movies, TV shows and people to discover. Explore now.</span>
            <form className='mt-6'>
              <input type="text" className="w-full h-12 mt-5 pl-5 rounded-3xl outline-none" placeholder="Search for a movie, tv show, person..." />
            </form>
          </div>
          <div>
            <h1 className='mb-4 mt-6 font-semibold text-2xl monterrat'>Trending</h1>
          </div>
          <div className='flex justify-center'>
            <div className='max-w-screen-2xl flex flex-row overflow-x-auto gap-x-5 gap-y-5 pb-10'>
              {
                trendingMovies.length <= 0 ? <></> : (
                  trendingMovies.map((movie) => {
                    return <MovieCard poster_path={movie.poster_path} title={movie.title} release_date={movie.release_date} key={movie.id}/>
                  })
                )
              }
            </div>
          </div>
          <LatestTrailers />
        </main>
      </div>
    </>
  )
}
